name: Lint and create release

on:
  push:
    branches: ['master']

jobs:
  bump_version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
  
      - name: Install dependencies
        run: npm ci
      
      - name: Set git config
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"

      - name: Run lint
        run: npm run lint

      - name: Run release
        env:
          GITHUB_TOKEN: ${{ secrets.SVC_POSA_PAT }}
        run: npm run release --ci --verbose

      - name: create-dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: trigger-cd
          client-payload: '{"action": "build-master"}'